"""initial schema with data_points data_sources anomalies enrichment_records

Revision ID: b7c11efca53b
Revises: 
Create Date: 2026-05-17 11:02:00.270854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.db.models import GUID

# revision identifiers, used by Alembic.
revision: str = 'b7c11efca53b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anomalies',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('metric', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('expected_value', sa.Float(), nullable=True),
    sa.Column('z_score', sa.Float(), nullable=True),
    sa.Column('methods_triggered', sa.JSON(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('anomalies', schema=None) as batch_op:
        batch_op.create_index('ix_anomalies_location', ['lat', 'lon'], unique=False)
        batch_op.create_index('ix_anomalies_severity', ['severity'], unique=False)
        batch_op.create_index('ix_anomalies_source_metric_ts', ['source', 'metric', 'timestamp'], unique=False)
        batch_op.create_index('ix_anomalies_timestamp', ['timestamp'], unique=False)

    op.create_table('data_points',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('metric', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_entity_id', sa.String(length=128), nullable=False),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', 'timestamp'),
    sa.UniqueConstraint('source', 'metric', 'source_entity_id', 'timestamp', name='uq_data_points_dedup')
    )
    with op.batch_alter_table('data_points', schema=None) as batch_op:
        batch_op.create_index('ix_data_points_location', ['lat', 'lon'], unique=False)
        batch_op.create_index('ix_data_points_metric', ['metric'], unique=False)
        batch_op.create_index('ix_data_points_source', ['source'], unique=False)
        batch_op.create_index('ix_data_points_source_entity', ['source', 'source_entity_id'], unique=False)
        batch_op.create_index('ix_data_points_source_metric_ts', ['source', 'metric', 'timestamp'], unique=False)
        batch_op.create_index('ix_data_points_timestamp', ['timestamp'], unique=False)

    op.create_table('data_sources',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('last_collected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('enrichment_records',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('anomaly_id', GUID(), nullable=False),
    sa.Column('context_window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('context_window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cross_source_summary_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['anomaly_id'], ['anomalies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('enrichment_records', schema=None) as batch_op:
        batch_op.create_index('ix_enrichment_records_anomaly_id', ['anomaly_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrichment_records', schema=None) as batch_op:
        batch_op.drop_index('ix_enrichment_records_anomaly_id')

    op.drop_table('enrichment_records')
    op.drop_table('data_sources')
    with op.batch_alter_table('data_points', schema=None) as batch_op:
        batch_op.drop_index('ix_data_points_timestamp')
        batch_op.drop_index('ix_data_points_source_metric_ts')
        batch_op.drop_index('ix_data_points_source_entity')
        batch_op.drop_index('ix_data_points_source')
        batch_op.drop_index('ix_data_points_metric')
        batch_op.drop_index('ix_data_points_location')

    op.drop_table('data_points')
    with op.batch_alter_table('anomalies', schema=None) as batch_op:
        batch_op.drop_index('ix_anomalies_timestamp')
        batch_op.drop_index('ix_anomalies_source_metric_ts')
        batch_op.drop_index('ix_anomalies_severity')
        batch_op.drop_index('ix_anomalies_location')

    op.drop_table('anomalies')
    # ### end Alembic commands ###
